config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "notes#index"

  resources :notes do
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
    root to: "notes#show"
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :note
  belongs_to :user

end

app/models/note.rb
class Note < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
  has_many :likes
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  
  has_many :notes
  has_many :likes
  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :passive_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
		@like = Like.all
		@note = Note.find(params[:note_id])
		note_likes = @note.likes.build
		note_likes.user = current_user
		note_owner = note_likes.note.user
		if note_likes.save
			UserMailer.new_like_email(note_owner).deliver_later
		end
  end
  
  def destroy
		@like = Like.all
		@note = Note.find(params[:note_id])
		like = Like.find(params[:id])
		like.destroy
  end
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  before_action :authenticate_user!, except: [:index]
  
  def index
    @notes = Note.all.order("created_at DESC")
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      flash[:notice] = "Note was saved successfully!"
    else
      flash.now[:alert] = "Note was not saved"
    end
    redirect_to user_path(current_user)
  end

  def show
    @note = Note.new
    @user = current_user
    @user_note = current_user.notes.order("created_at DESC")
    @user_following = @user.followings
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      flash[:notice] = "Note was updated successfully."
      redirect_to user_path(current_user)
    else
      flash.now[:alert] = "Failed to update note."
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    flash[:alert] = "Note was deleted."
    redirect_to user_path(current_user)
  end

  private

  def note_params
    params.require(:note).permit(:title, :body)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    new_follow = Relationship.new
    new_follow.update(follower_id: current_user.id, following_id: @user.id)
  end

  def destroy
    @user = User.find(params[:user_id])
    unfollow = Relationship.find(params[:id])
		unfollow.destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all
    @user = current_user
    @user_following = @user.followings
  end

  def show
    @user = User.find(params[:id])
    @user_note = @user.notes.order("updated_at DESC")
  end

  def followings
    @user  = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAcFinalAccessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <li class="nav-item nav-link"><%= link_to 'Notes App', root_path %></li>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">          
          <% if current_user %>
            <li class="nav-item navbar-nav"><%= link_to 'Home', user_path(current_user), class: 'nav-link' %></li>
            <li class="nav-item navbar-nav"><%= link_to 'Change password', edit_user_registration_path , class: 'nav-link' %></li>
            <li class="nav-item navbar-nav"><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %></li> 
          <% else %>
            <li class="navbar-nav nav-item"><%= link_to 'Register', new_user_registration_path, class: 'nav-link' %></li> 
            <li class="navbar-nav nav-item"><%= link_to 'Log in', new_user_session_path, class: 'nav-link' %></li>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
$('#likes-button_<%= @note.id %>').html('<%= j render 'shared/likes_button', note: @note %>');

app/views/likes/destroy.js.erb
$('#likes-button_<%= @note.id %>').html('<%= j render 'shared/likes_button', note: @note %>');

app/views/notes/edit.html.erb
    <%= form_for [@note] do |f| %>
      <div class="form-group">
        <%= f.text_field :title, class: 'form-control', rows: 1, placeholder: "Add a title!", maxlength: 50, id: 'textbox' %>
        <%= f.text_area :body, class: 'form-control', rows: 5, placeholder: "Add a description!", maxlength: 500, id: 'textbox' %>
      </div>
      <div class="form-group d-flex justify-content-end">
        <%= f.submit "Save", class: "btn btn-primary", id: "submitButton" %>
      </div>
    <% end %>

    <% if @note.errors.any? %>
      <%= @note.errors.full_messages.to_sentence%>
    <% end %>

app/views/notes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-3">
    <% @notes.each do |note| %>
      <div class="card">
        <div class="card-body">
          <small><b><%= note.user.name %></b> <i>@<%= link_to note.user.username, user_path(note.user) %></i> - <%= distance_of_time_in_words(note.created_at, Time.now)%> ago</small>
          <p>Title: <%= note.title %></p>
          <p>Description: <%= note.body %></p>
          <% if current_user %>
          <tr>
              <td>
                <div id="likes-button_<%= note.id %>">
                  <%= render "shared/likes_button", note: note %>
                </div>
              </td>
            </tr>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
</div>

app/views/notes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <h5><%= @user.name.capitalize %></h5>
          <h7><%= @user.username %></h7>
          <div>Joined <%= @user.created_at.strftime("%B %Y") %></div>
          <% if @user.notes.count <= 1 %>
            <div><%= @user.notes.count %> note </div>
          <% else %>
            <div><%= @user.notes.count %> notes </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-3 mt-3">
    <%= form_for [@note] do |f| %>
      <div class="form-group">
        <%= f.text_area :post, class: "form-control", rows: 5, placeholder: "Insert notes here", maxlength: 500, id: 'textbox'%>
      </div>
      <div class="form-group d-flex justify-content-end">
        <%= f.submit "Save", class: "btn btn-primary", id: "submitButton" %>
      </div>
    <% end %>
    <% @user_note.each do |note| %>
      <div class="card">
        <div class="card-body">
          <small><b><%= @user.name %></b> <i>@<%= link_to @user.username, user_path(@user) %></i> - <%= distance_of_time_in_words(note.created_at, Time.now)%> ago</small>
          <p><%= note.post %></p>
        </div>
      </div>
    <% end %>
    <% @user_following.each do |following| %>
      <% following.notes.each do |note| %>
        <div class="card">
          <div class="card-body">
            <small><b><%= following.name %></b><i> @<%= link_to following.username, user_path(following) %></i></small>
            <tr>
              <td>
                <div id="likes-button_<%= note.id %>">
                  <%= render "shared/likes_button", note: note %>
                </div>
              </td>
            </tr>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
        </div>
      </div>
    </div>
</div>

app/views/relationships/create.js.erb
$('#follow_<%= @user.id %>').html('<%= j render 'shared/follow_form', user: @user %>')

$('#followers_<%= @user.id %>').html('<%= j render 'shared/followers_count', user: @user %>');

app/views/relationships/destroy.js.erb
$('#follow_<%= @user.id %>').html('<%= j render 'shared/follow_form', user: @user %>')

$('#followers_<%= @user.id %>').html('<%= j render 'shared/followers_count', user: @user %>');

app/views/shared/_follow_form.html.erb
<% if current_relationship = Relationship.find_by(follower_id: current_user.id, following_id: user.id) %>

		<%= link_to user_relationship_path(user_id: user.id, id: current_relationship.id), method: :delete, class: 'btn btn-primary btn-unfollow', remote: true do %>
		 <span class="before">Following</span><span class="after">Unfollow</span>
		 <% end %>

<% else %><%= link_to "Follow", user_relationships_path(user), method: :post, class: 'btn btn-outline-primary', remote: true %>

<% end %>

app/views/shared/_followers_count.html.erb
<p><strong><%= link_to user.followings.count, followings_user_path(user) %></strong> following <strong><%= link_to user.followers.count, followers_user_path(user) %></strong> followers</p>

app/views/shared/_likes_button.html.erb
<% if note.likes.find_by(user_id: current_user.id)%>
    <% current_like = note.likes.find_by(user_id: current_user.id)%>
  <%= link_to 'Unlike', note_like_path(note_id: note.id, id: current_like.id), method: :delete, remote: true %>
<% else %>
  <%= link_to 'Like', note_likes_path(note_id: note.id), method: :post, remote: true %>
<% end %>

app/views/users/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <h5><%= @user.name.capitalize %></h5>
          <h7><%= @user.username %></h7>
          <div>Joined <%= @user.created_at.strftime("%B %Y") %></div>
          <% if @user.notes.count <= 1 %>
            <div><%= @user.notes.count %> note </div>
          <% else %>
            <div><%= @user.notes.count %> notes </div>
          <% end %>
          <div id="followers_<%= @user.id %>">
            <p><%= render partial: 'shared/followers_count', locals: {user: @user} %></p>
          </div>
          <% if @user != current_user %>
            <div id="follow_<%= @user.id %>">
              <p><%= render partial: 'shared/follow_form', locals: {user: @user} %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-3">
    <% @users.each do |follower| %>
      <div class="card">
        <div class="card-body">
        <small><b><%= follower.name %></b><i>@<%= link_to follower.username, user_path(follower) %></i></small>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <h5><%= @user.name.capitalize %></h5>
          <h7><%= @user.username %></h7>
          <div>Joined <%= @user.created_at.strftime("%B %Y") %></div>
          <% if @user.notes.count <= 1 %>
            <div><%= @user.notes.count %> note </div>
          <% else %>
            <div><%= @user.notes.count %> notes </div>
          <% end %>
          <div id="followers_<%= @user.id %>">
            <p><%= render partial: 'shared/followers_count', locals: {user: @user} %></p>
          </div>
          <% if @user != current_user %>
            <div id="follow_<%= @user.id %>">
              <p><%= render partial: 'shared/follow_form', locals: {user: @user} %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-3">
    <% @users.each do |following| %>
      <div class="card">
        <div class="card-body">
        <small><b><%= following.name %></b><i>@<%= link_to following.username, user_path(following) %></i></small>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <h5><%= @user.name.capitalize %></h5>
          <h7><%= @user.username %></h7>
          <div>Joined <%= @user.created_at.strftime("%B %Y") %></div>
          <% if @user.notes.count <= 1 %>
            <div><%= @user.notes.count %> note </div>
          <% else %>
            <div><%= @user.notes.count %> notes </div>
          <% end %>
        </div>
      </div>
   </div>
    <div class="col-md-3 mt-3">
    <% @users.each do |user| %>
      <div class="card">
        <div class="card-body">
          <small><b><%= user.name %></b><i> @<%= link_to user.username, user_path(user) %></i></small>
          <p>Latest Note: <%= user.notes.last.try(:post) %></p>
          <% if user != current_user %>
            <div id="follow_<%= user.id %>">
              <p><%= render partial: 'shared/follow_form', locals: {user: user} %></p>
            </div>
          <% end %>
          <% @user_following.each do |following| %>
            <% following.notes.each do |note| %>
            <div class="card">
              <div class="card-body">
                <small><b><%= following.name %></b><i> @<%= link_to following.username, user_path(following) %></i></small>
              </div>
            </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
        </div>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-3">
      <div class="card">
        <div class="card-body">
          <h5><%= @user.name.capitalize %></h5>
          <h7><%= @user.username %></h7>
          <div>Joined <%= @user.created_at.strftime("%B %Y") %></div>
          <% if @user.notes.count <= 1 %>
            <div><%= @user.notes.count %> note </div>
          <% else %>
            <div><%= @user.notes.count %> notes </div>
          <% end %>
          <div id="followers_<%= @user.id %>">
            <p><%= render partial: 'shared/followers_count', locals: {user: @user} %></p>
          </div>
          <% if @user != current_user %>
            <div id="follow_<%= @user.id %>">
              <p><%= render partial: 'shared/follow_form', locals: {user: @user} %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mt-3">
      <% if @user == current_user %>
        <%= form_for Note.new do |f| %>
          <div class="form-group">
          <%= f.text_field :title, class: 'form-control', rows: 1, placeholder: "Add a title!", maxlength: 50, id: 'textbox' %>
          <%= f.text_area :body, class: 'form-control', rows: 5, placeholder: "Add a description!", maxlength: 500, id: 'textbox' %>
          </div>
          <div class="form-group d-flex justify-content-end">
            <%= f.submit "Save", class: 'btn btn-primary', id: 'submitButtonId' %>
          </div>
        <% end %>
      <% end %>
      <% @user_note.each do |note| %>
        <div class="card">
          <div class="card-body">
            <p>Title: <%= note.title %></p>
            <p>Description: <%= note.body %></p>
            <% if @user == current_user %>
            <tr>
              <td>
                <%= link_to 'Edit', edit_note_path(note) %>
                <%= link_to 'Delete', note_path(note), method: :delete, data: {confirm:"Are you sure"} %>
              </td>
            </tr>
            <% else %>
            <tr>
              <td>
                <div id="likes-button_<%= note.id %>">
                  <%= render "shared/likes_button", note: note %>
                </div>
              </td>
            </tr>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>